Repository christianahvilla/das-ui, pull requests merged in 2021-09, with the labels that each got.

#22 Upgrade Material UI
  package-lock.json
  package.json
  src/stories/Button/CommonButton.jsx
  src/stories/Button/CommonButton.stories.jsx
  src/stories/Button/CommonButton.test.js
Labels: done, reviewed

#24 Add Search Bar
  package-lock.json
  package.json
  src/helpers/Constants.js
  src/stories/SearchBar/CommonSearchBar.jsx
  src/stories/SearchBar/CommonSearchBar.stories.jsx
  src/stories/SearchBar/CommonSearchBar.test.js
Labels: ready for review

#25 Add Text Field
  src/stories/TextField/CommonTextField.jsx
  src/stories/TextField/CommonTextField.stories.js
  src/stories/TextField/CommonTextField.test.js
Labels: done

#26 Add Progress
  src/stories/Progress/CommonProgress.jsx
  src/stories/Progress/CommonProgress.stories.js
  src/stories/Progress/CommonProgress.test.js
  src/stories/SearchBar/CommonSearchBar.test.js
  src/stories/TextField/CommonTextField.test.js
Labels: ready for review

#27 Feat/table
  package-lock.json
  package.json
  src/helpers/Constants.js
  src/helpers/constants.js
  src/helpers/icons.js
  src/stories/Checkbox/CommonCheckbox.jsx
  src/stories/Checkbox/CommonCheckbox.stories.jsx
  src/stories/Checkbox/CommonCheckbox.test.js
  src/stories/Icon/CommonIcon.jsx
  src/stories/Icon/CommonIcon.stories.jsx
  src/stories/Icon/CommonIcon.test.js
  src/stories/SearchBar/CommonSearchBar.jsx
  src/stories/SearchBar/CommonSearchBar.stories.jsx
  src/stories/Table/CommonTable.jsx
  src/stories/Table/CommonTable.stories.jsx
  src/stories/Table/CommonTable.test.js
Labels: ready for review

#28 Add Alert
  package-lock.json
  package.json
  src/helpers/types.js
  src/stories/Alert/CommonAlert.jsx
  src/stories/Alert/CommonAlert.stories.js
  src/stories/Alert/CommonAlert.test.js
Labels: ready for review
